guanbingking/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Text;
using System.Data;

namespace guanbingking.Controllers
{
    [Filters.AuthorizeFilter]
    [Filters.CrudAction]
    public class SuppliersController : Controller
    {
        //
        // GET: /Suppliers/

        public ActionResult Index()
        {
            return View();
        }

        //列表
        [HttpGet]
        public ActionResult List()
        {
            StringBuilder sb = new StringBuilder();
            int page = int.Parse(Request.QueryString["page"].ToString());
            int limit = int.Parse(Request.QueryString["limit"].ToString());

            string where = "1=1";
            if (!String.IsNullOrEmpty(Request.QueryString["name"]))
            {
                where += " and CompanyName like '%" + Request.QueryString["name"] + "%'";
            }

            DataTable dt = new BLL.Company().GetListByPage(where,"id",(page-1)*limit,page*limit).Tables[0];
            sb.Append("{\"status\": 200,\"message\": \"\",\"total\": "+new BLL.Company().GetRecordCount(where)+",\"rows\": {\"item\": [");
            for (int i = 0; i < dt.Rows.Count; i++)
            {
                if (i > 0) { sb.Append(","); }
                sb.Append("{\"id\":"+dt.Rows[i]["id"]+",\"companymame\":\"" + dt.Rows[i]["CompanyName"] + "\",\"address\":\"" + dt.Rows[i]["Address"] + "\",\"contact\":\"" + dt.Rows[i]["contact"] + "\",\"phone\":\"" + dt.Rows[i]["phone"] + "\"}");
            }
            sb.Append("]}}");

            return Content(sb.ToString());
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(Model.Company company)
        {
            company.Category = 1;
            if (new BLL.Company().Add(company)>0)
            {
                return Json(new { success = 0, msg = "提交成功" });
            }
            else
            {
                return Json(new { success=0,msg="提交失败"});
            }
        }

        [HttpGet]
        public ActionResult Edit(string id)
        {
            ViewData.Model = new BLL.Company().GetModel(int.Parse(id));
            return View();
        }

        [HttpPost]
        public ActionResult Edit(Model.Company company)
        {
            if (new BLL.Company().Update(company))
            {
                return Json(new { success = 0, msg = "提交成功" });
            }
            else
            {
                return Json(new { success = 0, msg = "提交失败" });
            }
        }

        [HttpPost]
        public ActionResult Del(string id)
        {
            if (new BLL.Company().Delete(int.Parse(id)))
            {
                return Json(new { success = 0, msg = "提交成功" });
            }
            else
            {
                return Json(new { success = 0, msg = "提交失败" });
            }
        }

        public ActionResult Show(string id)
        {
            ViewData.Model = new BLL.Company().GetModel(int.Parse(id));
            return View();
        }
    }
}

guanbingking/Views/Suppliers/Add.cshtml
@model guanbingking.Model.Company
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Add</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/Static/css/font.css">
    <link rel="stylesheet" href="/Static/css/xadmin.css">
    <script type="text/javascript" src="/Static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/Static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
            <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
            <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <script src="~/Static/js/jquery.min.js"></script>
</head>
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form">
                <div class="layui-form-item">
                    <label for="L_email" class="layui-form-label">
                        公司名称</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.CompanyName, new { required = "", autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">
                        <span class="x-red">*</span>公司的名称
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        详细地址</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.Address, new { autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">详细地址</div>
                </div>

                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        联系人</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.Contact, new { autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">法人/其他</div>
                </div>

                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        联系电话</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.Phone, new { autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">联系人的手机号码</div>
                </div>

                <div class="layui-form-item">
                    <label for="L_repass" class="layui-form-label"></label>
                    <button type="button" class="layui-btn" id="addbtn">增加</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        layui.use(['form', 'layer'],
            function () {
                var form = layui.form,
                layer = layui.layer;

                //异步提交
                $("#addbtn").click(function () {

                    if ($("#CompanyName").val().length == 0) {
                        layer.msg("请填写公司名称");
                        return false;
                    }
                    $.ajax({
                        url: '@Url.Action("Add")',
                        type: 'post',
                        data: $("form").serialize(),
                        dataType: 'json',
                        success: function (data) {
                            if (data.success == 0) {
                                //发异步，把数据提交给后端
                                layer.alert("增加成功", {
                                    icon: 6
                                },
                                function () {
                                    //关闭当前frame
                                    xadmin.close();

                                    // 可以对父窗口进行刷新 
                                    xadmin.father_reload();
                                });
                            }
                            else {
                                layer.msg("提交失败");
                            }
                        }
                    });
                });

            });

    </script>
</body>
</html>

guanbingking/Views/Suppliers/Edit.cshtml
@model guanbingking.Model.Company
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/Static/css/font.css">
    <link rel="stylesheet" href="/Static/css/xadmin.css">
    <script type="text/javascript" src="/Static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/Static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
            <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
            <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <script src="~/Static/js/jquery.min.js"></script>
</head>
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form">
                <div class="layui-form-item">
                    <label for="L_email" class="layui-form-label">
                        公司名称</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.CompanyName, new { required = "", autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">
                        <span class="x-red">*</span>公司的名称
                    </div>
                </div>
                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        详细地址</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.Address, new { autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">详细地址</div>
                </div>

                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        联系人</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.Contact, new { autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">法人/其他</div>
                </div>

                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        联系电话</label>
                    <div class="layui-input-inline">
                        @Html.TextBoxFor(company => company.Phone, new { autocomplete = "off", @class = "layui-input" })
                    </div>
                    <div class="layui-form-mid layui-word-aux">联系人的手机号码</div>
                </div>

                <div class="layui-form-item">
                    <label for="L_repass" class="layui-form-label"></label>
                    <button type="button" class="layui-btn" id="addbtn">保存</button>
                </div>
            </form>
        </div>
    </div>
    <script>
        layui.use(['form', 'layer'],
            function () {
                var form = layui.form,
                layer = layui.layer;

                //异步提交
                $("#addbtn").click(function () {

                    if ($("#CompanyName").val().length == 0) {
                        layer.msg("请填写公司名称");
                        return false;
                    }
                    $.ajax({
                        url: '@Url.Action("Edit","Suppliers")',
                        type: 'post',
                        data: $("form").serialize(),
                        dataType: 'json',
                        success: function (data) {
                            if (data.success == 0) {
                                //发异步，把数据提交给后端
                                layer.alert("修改成功", {
                                    icon: 6
                                },
                                function () {
                                    //关闭当前frame
                                    xadmin.close();

                                    // 可以对父窗口进行刷新 
                                    xadmin.father_reload();
                                });
                            }
                            else {
                                layer.msg("修改失败");
                            }
                        }
                    });
                });

            });

    </script>
</body>
</html>

guanbingking/Views/Suppliers/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/Static/css/font.css">
    <link rel="stylesheet" href="/Static/css/xadmin.css">
    <script src="/Static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/Static/js/xadmin.js"></script>
</head>
<body>
    <div class="x-nav">
        <span class="layui-breadcrumb">
            <a href="">首页</a>
            <a>
                <cite>供应商管理</cite></a>
        </span>
        <a class="layui-btn layui-btn-small" style="line-height: 1.6em; margin-top: 3px; float: right" onclick="location.reload()" title="刷新">
            <i class="layui-icon layui-icon-refresh" style="line-height: 30px"></i>
        </a>
    </div>
    <div class="layui-fluid">
        <div class="layui-row layui-col-space15">
            <div class="layui-col-md12">
                <div class="layui-card">
                    <div class="layui-card-body ">
                        <div class="layui-form layui-col-space5">
                            <div class="layui-input-inline layui-show-xs-block">
                                <input type="text" name="username" placeholder="名称" id="name" autocomplete="off" class="layui-input">
                            </div>
                            
                            <div class="layui-input-inline layui-show-xs-block">
                                <button class="layui-btn" lay-filter="sreach" onclick="query()">
                                    <i class="layui-icon">&#xe615;</i></button>
                            </div>
                            
                            @if(ViewBag.Add)
                            {
                                <button class="layui-btn" onclick="xadmin.open('添加供应商','@Url.Action("Add")',800,350)"><i class="layui-icon"></i>添加</button>
                            }
                        </div>
                    </div>
                    <div class="layui-card-body ">
                        <table class="layui-table layui-form" id="demo">
                        </table>
                    </div>

                </div>
            </div>
        </div>
    </div>

    <!--模板-->
    <script type="text/html" id="titleTpl">
        @if(ViewBag.Show){
        <a href="javascript:" onclick="show({{d.id}})" class="layui-table-link">查看</a>
        }
        @if(ViewBag.Edit){
        <a href="javascript:" onclick="edit({{d.id}})" class="layui-table-link">修改</a>
        }
        @if(ViewBag.Del){
        <a href="javascript:" onclick="del(this,{{d.id}})" class="layui-table-link">删除</a>
        }
    </script>
</body>
<script>
    layui.use(['laydate', 'form', 'table'],
    function () {
        var laydate = layui.laydate
        table = layui.table;

        table.render({
            elem: '#demo' //指定原始表格元素选择器（推荐id选择器）
            , height: 315 //容器高度
            , cols: [[
                { field: 'companymame', title: '名称' }
                , { field: 'address', title: '地址' }
                , { field: 'contact', title: '联系人' }
                , { field: 'phone', title: '联系电话' }
                , { title: '操作', templet: '#titleTpl',width:'125'}
            ]] //设置表头
            //,…… //更多参数参考右侧目录：基本参数选项
            , url: '@Url.Action("List")'
                , page: true
                , where: {
                    name: $("#name").val()
                }
                , response: {
                    statusCode: 200 //重新规定成功的状态码为 200，table 组件默认为 0
                }
                , parseData: function (res) { //将原始数据解析成 table 组件所规定的数据
                    return {
                        "code": res.status, //解析接口状态
                        "msg": res.message, //解析提示文本
                        "count": res.total, //解析数据长度
                        "data": res.rows.item //解析数据列表
                    };
                }
        });
    });

    function query() {
        //console.log("111")
        table.render({
            elem: '#demo' //指定原始表格元素选择器（推荐id选择器）
            , height: 315 //容器高度
            , cols: [[
                { field: 'companymame', title: '名称' }
                , { field: 'address', title: '地址' }
                , { field: 'contact', title: '联系人' }
                , { field: 'phone', title: '联系电话' }
                , { title: '操作', templet: '#titleTpl', width: '125' }
            ]] //设置表头
            //,…… //更多参数参考右侧目录：基本参数选项
            , url: '@Url.Action("List")'
                , page: true
                , where: {
                    name: $("#name").val()
                }
                , response: {
                    statusCode: 200 //重新规定成功的状态码为 200，table 组件默认为 0
                }
                , parseData: function (res) { //将原始数据解析成 table 组件所规定的数据
                    return {
                        "code": res.status, //解析接口状态
                        "msg": res.message, //解析提示文本
                        "count": res.total, //解析数据长度
                        "data": res.rows.item //解析数据列表
                    };
                }
        });
    }
    /*用户-删除*/
    function del(obj, id) {
        layer.confirm('确认要删除吗？',
        function () {
            //发异步删除数据
            $.ajax({
                url: '@Url.Action("del")',
                    type: 'post',
                    data: { id: id },
                    dataType: 'json',
                    success: function (data) {
                        if (data.success == 0) {
                            $(obj).parents("tr").remove();
                            layer.msg('已删除!', {
                                icon: 1,
                                time: 1000
                            });
                        }
                        else {
                            layer.msg("删除失败");
                        }
                    }
                });


            });
    }

    function edit(id)
    {
        xadmin.open('修改用户', '@Url.Action("Edit", "Suppliers")/'+id, 800, 350);
    }

    function show(id)
    {
        xadmin.open('用户信息', '@Url.Action("Show", "Suppliers")/' + id, 800, 350);
    }
</script>

</html>

guanbingking/Views/Suppliers/Show.cshtml
@model guanbingking.Model.Company
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
    <meta name="renderer" content="webkit">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=yes, minimum-scale=0.4, initial-scale=0.8,target-densitydpi=low-dpi" />
    <link rel="stylesheet" href="/Static/css/font.css">
    <link rel="stylesheet" href="/Static/css/xadmin.css">
    <script type="text/javascript" src="/Static/lib/layui/layui.js" charset="utf-8"></script>
    <script type="text/javascript" src="/Static/js/xadmin.js"></script>
    <!-- 让IE8/9支持媒体查询，从而兼容栅格 -->
    <!--[if lt IE 9]>
            <script src="https://cdn.staticfile.org/html5shiv/r29/html5.min.js"></script>
            <script src="https://cdn.staticfile.org/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
    <script src="~/Static/js/jquery.min.js"></script>
    <style>
        .l2 {
            text-align:left;
            width:auto;
        }
    </style>
</head>
<body>
    <div class="layui-fluid">
        <div class="layui-row">
            <form class="layui-form">
                <div class="layui-form-item">
                    <label class="layui-form-label">
                        公司名称：</label>
                    <label class="layui-form-label l2">
                        @Model.CompanyName
                        </label>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">
                        详细地址：</label>
                    <label class="layui-form-label l2">
                    @Model.Address
                        </label>
                </div>

                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        联系人：</label>
                    <label class="layui-form-label l2">
                    @Model.Contact
                        </label>
                </div>

                <div class="layui-form-item">
                    <label for="L_pass" class="layui-form-label">
                        联系电话：</label>
                    <label class="layui-form-label l2">
                    @Model.Phone
                        </label>
                </div>

            </form>
        </div>
    </div>
    
</body>
</html>